name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Clean
      run: dotnet clean TestCreator\TestCreator.sln --configuration Release && dotnet nuget locals all --clear
    - name: Restore dependencies
      run: dotnet restore
      working-directory: TestCreator
    - name: Build
      run: dotnet build TestCreator\TestCreator.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test TestCreator\TestCreator.sln --configuration Release --no-restore --verbosity normal
      
